name: Biographies for NEWSROOM_SIX

on:
  workflow_dispatch:
  schedule:
    - cron: "17 1,15 * * *" 

jobs:
  importer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache virtual environment
        uses: actions/cache@v4
        id: venv-cache
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}-
            venv-${{ runner.os }}-

      - name: Install dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/.venv
          source ~/.venv/bin/activate
          pip install --upgrade pip
          pip install requests bs4

      - name: Bios Newsroom Six
        env:
          MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
          NEWSROOM_VARIABLE: ${{ secrets.NEWSROOM_SIX }}
          QUOTE_TABLE: ${{ secrets.QUOTE_TABLE }}
          DATES_ENDPOINT: ${{ secrets.DATES_ENDPOINT }}
          LLM_SERVICE: ${{ secrets.LLM_SERVICE }}
          LLM_HEADER: ${{ secrets.LLM_HEADER }}
          BACKEND_API: ${{ secrets.BACKEND_API }}
          WK_DATA: ${{ secrets.WK_DATA }}
          SHOT_ENDPOINT: ${{ secrets.SHOT_ENDPOINT }}
          SHOT_ENDPOINT_SECRET: ${{ secrets.SHOT_ENDPOINT_SECRET }}
        run: |
          python person.py
          python biographies.py
