name: Cleanup People for NEWSROOM_FOUR

on:
  workflow_dispatch:
  schedule:
    - cron: "49 8 * * *"

jobs:
  importer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v6

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Cache Python Packages
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies or take from Cache
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: People Correct Newsroom Four
        env:
          MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
          NEWSROOM_VARIABLE: ${{ secrets.NEWSROOM_FOUR }}
          QUOTE_TABLE: ${{ secrets.QUOTE_TABLE }}
          BACKEND_API: ${{ secrets.BACKEND_API }}
        run: |
          python people_correction.py