name: Source Data for NEWSROOM_TWO

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "49 4 * * *"

jobs:
  importer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache virtual environment
        uses: actions/cache@v4
        id: venv-cache
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}-
            venv-${{ runner.os }}-

      - name: Install dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/.venv
          source ~/.venv/bin/activate
          pip install --upgrade pip
          pip install requests bs4

      - name: Source Data Newsroom Two
        env:
          MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
          NEWSROOM_VARIABLE: ${{ secrets.NEWSROOM_TWO }}
          QUOTE_TABLE: ${{ secrets.QUOTE_TABLE }}
          BACKEND_API: ${{ secrets.BACKEND_API }}
          SEARCH_API: ${{ secrets.SEARCH_API }}
        run: |
          python source_data.py