name: Run Importer for WECHO Stories

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "17 5 * * *" # every day at 5:17 am GMT

jobs:
  spacy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache Python Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies or take from Cache
        run: |
          python -m pip install --upgrade pip
          pip install requests
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Run Importer Script
        env:
          MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
        run: python main.py
